### ISSUE TITLE
Duplicate endpoint entries

### ISSUE THREAD

**Issue by checkaayush** [channelcat/sanic-openapi#60]
![screenshot from 2018-03-23 20-06-46](https://user-images.githubusercontent.com/4137581/37835276-c9468b12-2ed5-11e8-8b5f-c0338009d2c9.png)

For the garage example listed in readme, why are there 2 entries in generated swagger config? Or am I missing something and this is the expected behavior?

**Comment by DirkGuijt** [comment]
There is a 'strict_slashes' setting which is 'False' by default. That means that you can call the endpoints with or without the trailing slash, so they both show in the documentation as they are both valid. If you want to be more strict you can turn 'strict_slashes' on like this:

`app = Sanic(app_name, strict_slashes=True)`

**Comment by checkaayush** [comment]
Awesome. Thanks. :blush:

**Comment by autogestion** [comment]
@DirkGuijt  what if don't want be more strict with urls, but still want to get rid of duplications in swagger?

**Comment by DirkGuijt** [comment]
@autogestion It is probably by design that it shows in the openapi spec with ánd without slash if you're not strict about it (I didn't make that design decision btw :P I'm just guessing here). You can always change to code and make a PR if you want, which should get merged if enough people support it. Though I doubt anything will get merged, the maintainers seem to have completely vanished...
